spring:
#  kafka:
#    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: rithysak
    password: rithysak
    virtual-host: /
  main:
    allow-bean-definition-overriding: true

